name: Runs

on:
  push:
    branches: [ "stable" ]
  workflow_dispatch:
    branches: [ "stable" ]

jobs:
  build:
    name: Run
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Restore dependencies
      run: npm i tmi.js